DELETE http://localhost:8080/customers

Content-type: application/json
Accept: application/json

{"id": 10,"firstName": "Will","lastName": "Rogers","city": "Dallas","zipCode": 75082 "dateJoined": "June 14 2021"}